server:
  port: 8080
  address: 0.0.0.0  # 모든 IPv4 인터페이스에서 리스닝

spring:
  datasource:
      h2:
        console:
          enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
          path: /h2-console  # H2 Console? Path
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;MODE=MYSQL
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHb17
