spring:
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;MODE=MYSQL
      username: sa
      password:
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: moMQFUSHmEQLJ24OlDhj
            client-secret: HupMrYC8yt #TODO 외부 노출 방지 필요
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #고정값(운영일 때 profile에 맞춰 변경)
            authorization-grant-type: authorization_code
            scope: name , email
            client-name: Naver
          kakao:
            client-id: 1e8cf90e4a41d3250b08438a95b69f98
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao #고정값(운영일 때 profile에 맞춰 변경)
            authorization-grant-type: authorization_code
            scope: profile_nickname , account_email #profile_nickname
            client-name: Kakao
            provider: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHb17 #TODO 노출되지 않게 HOW?

# S3
#TODO 깃허브에 올리면 안됌 x -> 우선 github action secret 변수로 사용 가능한 지 해보고 안되면 다시 생각
cloud:
  aws:
    credentials:
      access-key:
      secret-key:




