spring:
  datasource:
      h2:
        console:
          enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
          path: /h2-console  # H2 Console? Path
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;MODE=MYSQL
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1e8cf90e4a41d3250b08438a95b69f98
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile #profile_nickname
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHb17
